<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Igor Boytsov</Authors>
    <Company>Crossdyne</Company>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.Year) Crossdyne</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/crossdyne/dotnet-generators</RepositoryUrl>
    <PackageProjectUrl>https://github.com/crossdyne/dotnet-generators</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    
    <PackageReadmeFile>README.md</PackageReadmeFile>
    
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>false</IncludeSource>
    <EmbedUntrackedSources>true</EmbedUntrackedSources> 
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md" 
          Pack="true" 
          PackagePath="\" 
          Condition="Exists('$(MSBuildThisFileDirectory)README.md')" />
  </ItemGroup>

  <ItemGroup Condition="'$(RepositoryType)' == 'git'">
    <PackageReference Include="Microsoft.SourceLink.GitHub"/>
  </ItemGroup>

  <PropertyGroup Condition="$(TargetFramework.EndsWith('-windows'))">
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>